cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

stages:
  - test
  - release

"PHP CS Fixer":
  stage: test
  image: ekreative/php-cs-fixer:2
  script:
    - php-cs-fixer fix --dry-run --config=.Build/.php_cs --diff

.unit_tests: &unit_tests
  stage: test
  image: php:$PHP_VERSION
  before_script:
    - apt-get update && apt-get install -y bash
    - bash ./.Build/docker_install.sh > /dev/null
    - composer install
  script:
    - ls -l
    - vendor/bin/phpunit -c ./.Build/UnitTests.xml
  artifacts:
    reports:
      junit: build/*-report.xml

"Unit Tests with PHP 7.2":
  <<: *unit_tests
  variables:
    PHP_VERSION: '7.2'

"Unit Tests with PHP 7.4":
  <<: *unit_tests
  variables:
    PHP_VERSION: '7.4'

"Upload to TER":
  stage: release
  image: composer:2
  only:
    - tags
  before_script:
    - apk add --update libxml2-dev
    - docker-php-ext-install soap
    - composer global require namelesscoder/typo3-repository-client
  script:
    - >
      if [ -n "$CI_COMMIT_TAG" ] && [ -n "$T3O_USERNAME" ] && [ -n "$T3O_PASSWORD" ]; then
        echo -e "Preparing upload of release ${CI_COMMIT_TAG} to TER\n"
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        # Upload
        TAG_MESSAGE=`git tag -n10 -l $CI_COMMIT_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${CI_COMMIT_TAG} to TER"
        /tmp/vendor/bin/upload . "$T3O_USERNAME" "$T3O_PASSWORD" "$TAG_MESSAGE"
      fi;

