include:
  - remote: 'https://git.spooner.io/spooner-web/gitlab-anybadge-creator/-/raw/main/anybadges.yml'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

stages:
  - test
  - badges
  - release

"PHP CS Fixer":
  stage: test
  image: ekreative/php-cs-fixer:2
  script:
    - php-cs-fixer fix --dry-run --config=.Build/.php_cs --diff

"PHP Static Analyzer":
  stage: test
  image: composer:1
  before_script:
    - composer global require phpstan/phpstan
  script:
    - composer install
    - /tmp/vendor/bin/phpstan analyse -l 4 -c .Build/phpstan.neon

"PHP Rector Analyzer":
  stage: test
  image: composer:1
  before_script:
    - composer install
    - mkdir build
  script:
    - vendor/bin/rector process --config .Build/rector.php --dry-run --output-format=checkstyle > build/rector.xml
  allow_failure: true
  artifacts:
    reports:
      junit: build/rector.xml

"Create Badge":
  stage: badges
  script:
    - latest_version=$(git describe --abbrev=0)
    - anybadge -l "Latest Version" -v $latest_version -f latestVersion.svg -c blue

.unit_tests: &unit_tests
  stage: test
  image: php:$PHP_VERSION
  before_script:
    - apt-get update && apt-get install -y bash
    - bash ./.Build/docker_install.sh > /dev/null
    - composer install
  script:
    - ls -l
    - vendor/bin/phpunit -c ./.Build/phpunit.xml
  artifacts:
    reports:
      junit: build/*-report.xml

"Unit Tests with PHP 7.2":
  <<: *unit_tests
  variables:
    PHP_VERSION: '7.2'

"Unit Tests with PHP 7.4":
  <<: *unit_tests
  variables:
    PHP_VERSION: '7.4'

"Mutation Tests":
  stage: test
  image: php:7.4
  variables:
    GIT_STRATEGY: "clone"
  allow_failure: true
  before_script:
    - set -xe
    - apt-get update -yqq
    - apt-get install git unzip zlib1g-dev libzip-dev -yqq
    - docker-php-ext-install zip
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export TYPO3_PATH_WEB="$PWD/private"
    - composer config cache-dir /cache/composer
  script:
    - composer install --ignore-platform-reqs
    # Have to install it here instead of in composer.json the version using the json output isn't compatible with PHP 7.2
    - composer require --dev infection/infection
    - ./vendor/bin/infection --min-msi=80 --min-covered-msi=80 --threads=4
  artifacts:
    when: always
    paths:
      - build/infection-log.json
    expire_in: 30 min

"Mutation Badges":
  stage: badges
  image: python:3.9
  allow_failure: true
  needs: ["Mutation Tests"]
  before_script:
    - echo "Python other dependencies installation"
    - pip3 install anybadge
    - apt update -y
    - apt install -y jq bc
  script:
    - mkdir badges
    - cd badges
    - mutation_msi=$(cat ../build/infection-log.json | jq .stats.msi)
    - anybadge -l "Mutation MSI" -v $mutation_msi -f mutation_msi.svg 50=red 90=yellow
    - mutation_mcc=$(cat ../build/infection-log.json | jq .stats.mutationCodeCoverage)
    - anybadge -l "Mutation MCC" -v $mutation_mcc -f mutation_mcc.svg 50=red 90=yellow
    - mutation_ccmsi=$(cat ../build/infection-log.json | jq .stats.coveredCodeMsi)
    - anybadge -l "Mutation CCMSI" -v $mutation_ccmsi -f mutation_ccmsi.svg 50=red 90=yellow
  artifacts:
    paths:
      - badges/
    when: always
    expire_in: 4 weeks

"Upload to TER":
  stage: release
  image: composer:2
  only:
    - tags
  before_script:
    - apk add --update libxml2-dev
    - docker-php-ext-install soap
    - composer global require namelesscoder/typo3-repository-client
  script:
    - >
      if [ -n "$CI_COMMIT_TAG" ] && [ -n "$T3O_USERNAME" ] && [ -n "$T3O_PASSWORD" ]; then
        echo -e "Preparing upload of release ${CI_COMMIT_TAG} to TER\n"
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        # Upload
        TAG_MESSAGE=`git tag -n10 -l $CI_COMMIT_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${CI_COMMIT_TAG} to TER"
        /tmp/vendor/bin/upload . "$T3O_USERNAME" "$T3O_PASSWORD" "$TAG_MESSAGE"
      fi;
